version: '2'
services:
    deip-client:
        build: .
        container_name: "deip-client"
        restart: always
        volumes:
            - '/etc/letsencrypt:/ssl:ro'
        ports:
            - "80:80"
            - "443:443"