import {
  EXPERTISE_CONTRIBUTION_TYPE,
  ECI_STAT_PERIOD_STEP_TYPE,
  CONTRACT_AGREEMENT_TYPE,
  USER_NOTIFICATION_TYPE,
  PROJECT_CONTENT_TYPES,
  PROJECT_CONTENT_STATUS,
  USER_PROFILE_STATUS,
  AWARD_STATUS,
  AWARD_RECIPIENT_STATUS,
  AWARD_WITHDRAWAL_REQUEST_STATUS,
  ASSESSMENT_CRITERIA_TYPE,
  USER_BOOKMARK_TYPE,
  PROJECT_CONTENT_FORMAT,
  SIGN_UP_POLICY,
  PROPOSAL_STATUS
} from '@deip/constants';
import { projectContentTypes } from '@deip/project-content-service';
import { createEnum } from '@deip/toolbox';


// TODO: remove after migration

const PROPOSAL_TYPES = createEnum({
  CREATE_PROJECT: 14,
  INVITE_MEMBER: 12,
  EXCLUDE_MEMBER: 13,
  TRANSFER: 2,
  CREATE_PROJECT_TOKEN_SALE: 19,
  CREATE_PROJECT_MATERIAL: 16,
  UPDATE_TEAM: 1,
  UPDATE_PROJECT: 15
});

const proposalTypesLabels = {
  [PROPOSAL_TYPES.CREATE_PROJECT]: 'Start new project',
  [PROPOSAL_TYPES.INVITE_MEMBER]: 'Invite new member to team',
  [PROPOSAL_TYPES.EXCLUDE_MEMBER]: 'Exclude member from team',
  [PROPOSAL_TYPES.TRANSFER]: 'Transfer team funds',
  [PROPOSAL_TYPES.CREATE_PROJECT_TOKEN_SALE]: 'Schedule project fundraising campaign',
  [PROPOSAL_TYPES.CREATE_PROJECT_MATERIAL]: 'Publish project results',
  [PROPOSAL_TYPES.UPDATE_TEAM]: 'Update group meta',
  [PROPOSAL_TYPES.UPDATE_PROJECT]: 'Update project meta'
};

const LOC_PROPOSAL_TYPES = createEnum({
  CREATE_PROJECT: 1,
  UPDATE_PROJECT: 2,
  CREATE_PROJECT_MATERIAL: 3,
  CREATE_PROJECT_TOKEN_SALE: 4,
  UPDATE_TEAM: 5,
  INVITE_MEMBER: 6,
  EXCLUDE_MEMBER: 7,
  TRANSFER_ASSET: 8,
  EXPRESS_LICENSE_REQUEST: 9,
  ASSET_EXCHANGE_REQUEST: 10,
  PROJECT_NDA: 11,
  PROJECT_TOKEN_SALE_PROPOSAL: 12,
  CONTRACT_AGREEMENT_PROPOSAL: 13
});

export {
  PROPOSAL_TYPES,
  proposalTypesLabels,
  projectContentTypes,
  EXPERTISE_CONTRIBUTION_TYPE,
  AWARD_STATUS,
  AWARD_RECIPIENT_STATUS,
  AWARD_WITHDRAWAL_REQUEST_STATUS,
  ASSESSMENT_CRITERIA_TYPE,
  ECI_STAT_PERIOD_STEP_TYPE,
  PROPOSAL_STATUS,
  LOC_PROPOSAL_TYPES,
  PROJECT_CONTENT_TYPES,
  PROJECT_CONTENT_STATUS,
  CONTRACT_AGREEMENT_TYPE,
  USER_NOTIFICATION_TYPE,
  USER_PROFILE_STATUS,
  USER_BOOKMARK_TYPE,
  PROJECT_CONTENT_FORMAT,
  SIGN_UP_POLICY
};
