import Vue from 'vue';
import TeamActivityLogList from './ResearchGroupActivityLogList';
import ProjectProposalActivityLogEntry from './components/ResearchProposalActivityLogEntry';
import ProjectContentProposalActivityLogEntry from './components/ResearchContentProposalActivityLogEntry';
import InviteProposalActivityLogEntry from './components/InviteProposalActivityLogEntry';
import TokenSaleProposalActivityLogEntry from './components/TokenSaleProposalActivityLogEntry';
import ProposalVoteActivityLogEntry from './components/ProposalVoteActivityLogEntry';
import InvitationApprovedActivityLogEntry from './components/InvitationApprovedActivityLogEntry';
import InvitationRejectedActivityLogEntry from './components/InvitationRejectedActivityLogEntry';
import ProjectContentExpertReviewActivityLogEntry from './components/ResearchContentExpertReviewActivityLogEntry';
import ProjectContentExpertReviewRequestActivityLogEntry from './components/ResearchContentExpertReviewRequestActivityLogEntry';

Vue.component('team-activity-log-list', TeamActivityLogList);
Vue.component('project-proposal-activity-log-entry', ProjectProposalActivityLogEntry);
Vue.component('project-content-proposal-activity-log-entry', ProjectContentProposalActivityLogEntry);
Vue.component('invite-proposal-activity-log-entry', InviteProposalActivityLogEntry);
Vue.component('token-sale-proposal-activity-log-entry', TokenSaleProposalActivityLogEntry);
Vue.component('proposal-vote-activity-log-entry', ProposalVoteActivityLogEntry);
Vue.component('invitation-approved-activity-log-entry', InvitationApprovedActivityLogEntry);
Vue.component('invitation-rejected-activity-log-entry', InvitationRejectedActivityLogEntry);
Vue.component('project-content-expert-review-activity-log-entry', ProjectContentExpertReviewActivityLogEntry);
Vue.component('project-content-expert-review-request-activity-log-entry', ProjectContentExpertReviewRequestActivityLogEntry);
